project:
  type: website
  output-dir: docs
website:
  title: "presentation-mars.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mars.qmd
        text: presentation-mars

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



